import type { Activity, ExerciseGoal, ExerciseMeasure } from '@forjd/domain';

import type { LiveExercise } from './live-session';

/**
 * Hands a session to the live screen (Phase 3H).
 *
 * The same plain in-memory module `builder-handoff.ts` already uses, and for the same reason
 * spelled out there: expo-router has no built-in way to pass a structured value between
 * screens, and a whole session -- every exercise, every prescribed set -- is far past what
 * belongs in a URL parameter.
 *
 * Kept separate from `builder-handoff.ts` rather than folded into it. That module carries two
 * *builder* concerns (a picked exercise, a template prefill); this carries a started session.
 * Sharing one module would couple two flows that have no reason to change together.
 *
 * **The id is generated by the caller, not here**, because it is also the sync idempotency key
 * (`WorkoutSession.id`) -- the session that gets uploaded must be the one that was started,
 * even if the live screen is unmounted and remounted in between.
 */
export interface PendingLiveSession {
  id: string;
  templateId: string | null;
  name: string;
  activity: Activity;
  exercises: LiveExercise[];
}

let pending: PendingLiveSession | null = null;

export function setPendingLiveSession(session: PendingLiveSession): void {
  pending = session;
}

/** Returns the pending session and clears it -- consumed once, like the builder's own handoff. */
export function consumePendingLiveSession(): PendingLiveSession | null {
  const value = pending;
  pending = null;
  return value;
}

/**
 * What the summary screen shows after a workout (Phase I).
 *
 * Deliberately the *computed* figures rather than the whole session: the summary is a read-only
 * report, and handing it the live session would invite a future edit there to write back into a
 * workout that has already been enqueued for upload.
 */
export interface CompletedSummary {
  name: string;
  durationSeconds: number;
  volumeKg: number;
  completedSetCount: number;
  /** For resolving muscles worked from the on-device catalogue. */
  exerciseIds: string[];
}

let completedSummary: CompletedSummary | null = null;

export function setCompletedSummary(summary: CompletedSummary): void {
  completedSummary = summary;
}

/**
 * Read, not consumed: the summary screen re-renders as its muscle tally resolves, and each
 * render must still see the figures. It is cleared explicitly on the way out instead.
 */
export function getCompletedSummary(): CompletedSummary | null {
  return completedSummary;
}

/** Called when the athlete leaves the summary, so a finished workout is not shown again. */
export function clearCompletedSummary(): void {
  completedSummary = null;
}

/**
 * An exercise picked from `library.tsx?pick=live` to be added to the session in progress.
 * Mirrors the builder's own picked-exercise slot: the library sets it and calls `router.back()`,
 * and the live screen consumes it on focus.
 */
let pickedForLive: PickedForLive | null = null;

export interface PickedForLive {
  exerciseId: string;
  name: string;
  measure: ExerciseMeasure;
  goal: ExerciseGoal | null;
}

export function setPickedExerciseForLive(exercise: PickedForLive): void {
  pickedForLive = exercise;
}

export function consumePickedExerciseForLive(): PickedForLive | null {
  const value = pickedForLive;
  pickedForLive = null;
  return value;
}

/**
 * What the rest screen needs beyond its countdown: the design's "Up next" block, which names
 * the next open set. Read rather than consumed -- the rest screen may re-render several times
 * over ninety seconds, and each one must still know what is coming.
 */
export interface RestContext {
  seconds: number;
  upNextName: string | null;
  upNextDetail: string | null;
}

let restContext: RestContext | null = null;

export function setRestContext(context: RestContext): void {
  restContext = context;
}

export function getRestContext(): RestContext | null {
  return restContext;
}

/** What the timed-set screen is counting down, and which set it will tick when it reaches zero. */
export interface TimerContext {
  exerciseIndex: number;
  setIndex: number;
  exerciseName: string;
  seconds: number;
}

let timerContext: TimerContext | null = null;

export function setTimerContext(context: TimerContext): void {
  timerContext = context;
}

export function getTimerContext(): TimerContext | null {
  return timerContext;
}

/**
 * The timed-set screen's *return* channel. It runs on its own route, so it cannot tick the set
 * directly -- it records which set finished, and the live screen consumes that when it regains
 * focus. Consumed once, so returning to the live screen a second time cannot double-tick.
 */
let completedTimedSet: { exerciseIndex: number; setIndex: number } | null = null;

export function setCompletedTimedSet(result: { exerciseIndex: number; setIndex: number }): void {
  completedTimedSet = result;
}

export function consumeCompletedTimedSet(): { exerciseIndex: number; setIndex: number } | null {
  const value = completedTimedSet;
  completedTimedSet = null;
  return value;
}
